export const sidebarLinks = [
  {
    imgURL: "/assets/icons/home.svg",
    route: "/",
    label: "Home",
    category: "Core",
  },
  {
    imgURL: "/assets/icons/wallpaper.svg",
    route: "/explore",
    label: "Explore",
    category: "Core",
  },
  {
    imgURL: "/assets/icons/people.svg",
    route: "/all-users",
    label: "People",
    category: "Core",
  },
  {
    imgURL: "/assets/icons/bookmark.svg",
    route: "/saved",
    label: "Saved",
    category: "Core",
  },
  {
    imgURL: "/assets/icons/gallery-add.svg",
    route: "/create-post",
    label: "Create Post",
    category: "Core",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/my-profile",
    label: "My Profile",
    category: "Academic",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/courses",
    label: "Courses",
    category: "Academic",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/course-schedule",
    label: "Schedule",
    category: "Academic",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/classmates",
    label: "Classmates",
    category: "Academic",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/study-groups",
    label: "Study Groups",
    category: "Study",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/assignments",
    label: "Assignments",
    category: "Study",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/group-projects",
    label: "Group Projects",
    category: "Study",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/qa-forum",
    label: "Q&A Forum",
    category: "Study",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/notes",
    label: "Notes",
    category: "Resources",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/projects",
    label: "Projects",
    category: "Resources",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/tutoring",
    label: "Tutoring",
    category: "Resources",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/resources",
    label: "Resources",
    category: "Resources",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/campus-map",
    label: "Campus Map",
    category: "Campus",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/dining",
    label: "Dining",
    category: "Campus",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/library",
    label: "Library",
    category: "Campus",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/facilities",
    label: "Facilities",
    category: "Campus",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/clubs",
    label: "Clubs",
    category: "Social",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/interest-groups",
    label: "Interest Groups",
    category: "Social",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/polls",
    label: "Polls",
    category: "Social",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/memes",
    label: "Memes",
    category: "Social",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/confessions",
    label: "Confessions",
    category: "Social",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/network",
    label: "Network",
    category: "Social",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/jobs",
    label: "Jobs",
    category: "Career",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/alumni",
    label: "Alumni",
    category: "Career",
  },
  {
    imgURL: "/assets/icons/add-post.svg",
    route: "/research-startups",
    label: "Research & Startups",
    category: "Career",
  },
];

export const bottombarLinks = [
  {
    imgURL: "/assets/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/assets/icons/wallpaper.svg",
    route: "/explore",
    label: "Explore",
  },
  {
    imgURL: "/assets/icons/bookmark.svg",
    route: "/saved",
    label: "Saved",
  },
  {
    imgURL: "/assets/icons/gallery-add.svg",
    route: "/create-post",
    label: "Create",
  },
];
